/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "LED_yellow_aliases.h"
#include "LED_yellow.h"
#include "LED_green_aliases.h"
#include "LED_green.h"
#include "IRQ_BUTTON.h"
#include "BUTTON_1_aliases.h"
#include "BUTTON_1.h"
#include "WaveDAC.h"
#include "AnalogOutFromDAC_aliases.h"
#include "AnalogOutFromDAC.h"
#include "Debounce_Clock.h"
#include "UART.h"
#include "IRQ_UART.h"
#include "ADC_DelSig.h"
#include "DMA_ForAdc_dma.h"
#include "IRQ_DMA.h"
#include "InputToAdc_aliases.h"
#include "InputToAdc.h"
#include "WaveDAC_DacClk.h"
#include "WaveDAC_Wave1_DMA_dma.h"
#include "WaveDAC_Wave2_DMA_dma.h"
#include "WaveDAC_VDAC8.h"
#include "WaveDAC_BuffAmp.h"
#include "UART_IntClock.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

